### ISSUE TITLE
Pubsub: handle stream closed

### ISSUE THREAD

**Issue by mhchia** [libp2p/py-libp2p#306]
After reviewing the PR https://github.com/libp2p/py-libp2p/pull/299#discussion_r326230742,   I found that the stream exceptions are not handled completely in the current codebase. We should revisit it and add tests for the situation when a pubsub stream is closed/reset.

### Reference
- Go implementation: https://github.com/libp2p/go-libp2p-pubsub/blob/master/comm.go#L38-L46

**Comment by moshemalawach** [comment]
Example exception I'm getting while trying to write a message:
```

2019-10-14 10:17:57 [ERROR] P2P.peers: Can't publish alive message
Traceback (most recent call last):
  File "/home/jon/virtualenvs/pyaleph/py-libp2p/libp2p/network/stream/net_stream.py", line 59, in write
    return await self.muxed_stream.write(data)
  File "/home/jon/virtualenvs/pyaleph/py-libp2p/libp2p/stream_muxer/mplex/mplex_stream.py", line 149, in write
    raise MplexStreamClosed(f"cannot write to closed stream: data={data}")
libp2p.stream_muxer.mplex.exceptions.MplexStreamClosed: cannot write to closed stream: data=b'\xb0\x01\x12\xad\x01\n"\x12 \xa7J\xb1\x
f0\xcaj\x84@\xe1\xa27\xe2\x0bv\x15t;\xe2\x13!\x0e\x9c\x8d\x13{\xb0[\x06\x1bA\xfcY\x12v{"address":"http://***","intere
sts":null,"peer_type":"HTTP","version":"0.0.post0.dev5+g8f7c4e8.dirty"}\x1a\x08\x15\xcd\x08\xa3d\xe9\x0e1"\x05ALIVE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jon/virtualenvs/pyaleph/pyaleph/src/aleph/services/p2p/peers.py", line 27, in publish_host
    await psub.publish(topic, msg)
  File "/home/jon/virtualenvs/pyaleph/py-libp2p/libp2p/pubsub/pubsub.py", line 409, in publish
    await self.push_msg(self.host.get_id(), msg)
  File "/home/jon/virtualenvs/pyaleph/py-libp2p/libp2p/pubsub/pubsub.py", line 481, in push_msg
    await self.router.publish(msg_forwarder, msg)
  File "/home/jon/virtualenvs/pyaleph/py-libp2p/libp2p/pubsub/floodsub.py", line 88, in publish
    await stream.write(encode_varint_prefixed(rpc_msg.SerializeToString()))
  File "/home/jon/virtualenvs/pyaleph/py-libp2p/libp2p/network/stream/net_stream.py", line 61, in write
    raise StreamClosed from error
libp2p.network.stream.exceptions.StreamClosed
```

As a side note, this means that my routines that periodically try to reconnect to host to which we have been disconnected from, fails (as a call to host.connect(multinfo) returns immediately if the host is still in the connected list).
We should perhaps disconnect from it on the host/swarm side when this happens?

**Comment by mhchia** [comment]
> this means that my routines that periodically try to reconnect to host to which we have been disconnected from, fails (as a call to host.connect(multinfo) returns immediately if the host is still in the connected list).

This is pretty strange because a disconnected peer should have been removed from the peer list.

> We should perhaps disconnect from it on the host/swarm side when this happens?

IMO we should avoid this from happening(i.e. connecting a peer which we already disconnected but haven't been removed from the peer list).
