### ISSUE TITLE
Unable to use on OSX

### ISSUE THREAD

**Issue by robvanmieghem** [libp2p/py-libp2p#423]
## What was wrong?

```py
import libp2p
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rob/workspace/github.com/libp2p/py-libp2p/libp2p/__init__.py", line 3, in <module>
    from libp2p.host.basic_host import BasicHost
  File "/Users/rob/workspace/github.com/libp2p/py-libp2p/libp2p/host/basic_host.py", line 5, in <module>
    from async_service import background_trio_service
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/async_service/__init__.py", line 1, in <module>
    from .abc import ManagerAPI, ServiceAPI  # noqa: F401
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/async_service/abc.py", line 4, in <module>
    import trio_typing
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/trio_typing/__init__.py", line 6, in <module>
    import trio as _trio
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/trio/__init__.py", line 18, in <module>
    from ._core import (
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/trio/_core/__init__.py", line 27, in <module>
    from ._run import (
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.8/lib/python3.8/site-packages/trio/_core/_run.py", line 2325, in <module>
    raise NotImplementedError("unsupported platform")
NotImplementedError: unsupported platform

```

### Environment
macOS Catalina
python 3.8

**Comment by ShadowJonathan** [comment]
Looks like `trio` doesn't run on your platform, and this snippet is causing the issue:

```
if sys.platform == "win32":
    from ._io_windows import WindowsIOManager as TheIOManager
    from ._generated_io_windows import *
elif sys.platform == "linux" or (not TYPE_CHECKING and hasattr(select, "epoll")):
    from ._io_epoll import EpollIOManager as TheIOManager
    from ._generated_io_epoll import *
elif TYPE_CHECKING or hasattr(select, "kqueue"):
    from ._io_kqueue import KqueueIOManager as TheIOManager
    from ._generated_io_kqueue import *
else:  # pragma: no cover
    raise NotImplementedError("unsupported platform")
```

**Comment by dhuseby** [comment]
Looks like it does now: https://ports.macports.org/port/py-trio/

**Comment by kazzmir** [comment]
Tested on my intel macmini and it works
```
$ uname -a
Darwin Jons-Mac-mini.attlocal.net 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
$ python3 -V
Python 3.9.6
$ pip install libp2p
$ pip freeze
libp2p==0.2.0
trio==0.27.0
```

The ping example works
```
% python ping.py 
Run this from the same folder in another console:

python ping.py -p 8001 -d /ip4/127.0.0.1/tcp/8000/p2p/Qmcs93UiBLvMaqRR1Bp12sVDSaZ242XHQxwfpFUpHFuf71

Waiting for incoming connection...

received ping from QmSfGP1FNeMimyL2Aktmpdkc63gJ6rkkeTLQCN2J5Q63tZ
responded with pong to QmSfGP1FNeMimyL2Aktmpdkc63gJ6rkkeTLQCN2J5Q63tZ
```

**Comment by dhuseby** [comment]
Thank you @kazzmir
